import React, { useEffect, useState } from "react";
import {
  getCategoriesByProvider,
  getProviderSummary,
} from "../sevice/customerService";

const ProviderCard = ({ provider }) => {
  const [services, setServices] = useState([]);
  const [summary, setSummary] = useState("");

  useEffect(() => {
    const fetchServices = async () => {
      try {
        const data = await getCategoriesByProvider(provider.providerId);
        //const data = await res.json();
        setServices(data);
      } catch (err) {
        console.error("Failed to fetch services:", err);
      }
    };

    const fetchSummary = async () => {
      try {
        const data = await getProviderSummary(provider.providerId);
        setSummary(data.summary);
      } catch (err) {
        console.error("Failed to fetch summary:", err);
      }
    };

    fetchServices();
    fetchSummary();
  }, [provider.providerId]);

  return (
    <div className="bg-white shadow-md rounded-xl p-6 space-y-4 hover:shadow-lg transition-shadow">
      {/* Header: Avatar + Name */}
      <div className="flex items-center gap-4">
        <div className="w-14 h-14 rounded-full bg-indigo-100 flex items-center justify-center font-bold text-indigo-600 text-xl">
          {provider.fullName.charAt(0)}
        </div>
        <div>
          <h3 className="text-lg font-semibold">{provider.fullName}</h3>
          <p className="text-sm text-gray-500">{provider.location}</p>
        </div>
      </div>

      {/* Summary generated By AI base on Reviews*/}
      {summary && (
        <div className="bg-gray-50 p-3 rounded-lg text-gray-800 text-sm">
          <h4 className="font-semibold mb-1">Summary "Ai Generated":</h4>
          <p>{summary}</p>
        </div>
      )}

      {/* Info */}
      <p className="text-gray-700">Biography: {provider.biography}</p>
      <div className="flex gap-4 text-sm text-gray-600">
        <span>Experience: {provider.yearOfExperience} yrs</span>
        <span>Trust Score: {provider.trustScore ?? "N/A"}</span>
        <span>Phone: {provider.phoneNumber}</span>
      </div>

      {/* Services */}
      <div>
        <h4 className="font-semibold text-gray-800 mb-2">Services:</h4>
        {services.length > 0 ? (
          <ul className="list-disc list-inside space-y-1 text-gray-700">
            {services.map((s) => (
              <li key={s.categoryId}>
                {s.categoryName} ${s.priceMin} - ${s.priceMax}
              </li>
            ))}
          </ul>
        ) : (
          <p className="text-gray-400">No services available</p>
        )}
      </div>
    </div>
  );
};

export default ProviderCard;
